"""baseline_completo

Revision ID: d93ac0ca2d1c
Revises: 
Create Date: 2026-07-06 15:15:14.941794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd93ac0ca2d1c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permisos_codigo'), 'permisos', ['codigo'], unique=True)
    op.create_index(op.f('ix_permisos_id'), 'permisos', ['id'], unique=False)
    op.create_table('puertos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_puertos_id'), 'puertos', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('es_sistema', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_nombre'), 'roles', ['nombre'], unique=True)
    op.create_table('carpetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('puerto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puerto_id'], ['puertos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_carpetas_id'), 'carpetas', ['id'], unique=False)
    op.create_index(op.f('ix_carpetas_puerto_id'), 'carpetas', ['puerto_id'], unique=False)
    op.create_table('roles_permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rol_id', 'permiso_id', name='uq_roles_permisos_rol_permiso')
    )
    op.create_index(op.f('ix_roles_permisos_id'), 'roles_permisos', ['id'], unique=False)
    op.create_index(op.f('ix_roles_permisos_permiso_id'), 'roles_permisos', ['permiso_id'], unique=False)
    op.create_index(op.f('ix_roles_permisos_rol_id'), 'roles_permisos', ['rol_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('guid', sa.String(length=100), nullable=True),
    sa.Column('user_type', sa.Enum('AD', 'LOCAL', name='tipousuario'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVO', 'INACTIVO', name='estadousuario'), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_rol_id'), 'users', ['rol_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('accion', sa.Enum('LOGIN_EXITOSO', 'LOGIN_FALLIDO', 'CERRAR_SESION', 'SESION_EXPIRADA', 'TRANSFERENCIA_CREADA', 'TRANSFERENCIA_ELIMINADA', 'DESCARGA_REALIZADA', name='accionauditoria'), nullable=False),
    sa.Column('detalle', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('agente', sa.String(length=500), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_creado_en'), 'audit_logs', ['creado_en'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('recipient', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.Column('max_downloads', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('carpeta_id', sa.Integer(), nullable=True),
    sa.Column('puerto_id', sa.Integer(), nullable=True),
    sa.Column('marino', sa.String(length=255), nullable=True),
    sa.Column('titulo_original', sa.String(length=255), nullable=True),
    sa.Column('mensaje_original', sa.Text(), nullable=True),
    sa.Column('destinatario_original', sa.String(length=255), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['carpeta_id'], ['carpetas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['puerto_id'], ['puertos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfers_carpeta_id'), 'transfers', ['carpeta_id'], unique=False)
    op.create_index('ix_transfers_expires_at', 'transfers', ['expires_at'], unique=False)
    op.create_index(op.f('ix_transfers_id'), 'transfers', ['id'], unique=False)
    op.create_index(op.f('ix_transfers_puerto_id'), 'transfers', ['puerto_id'], unique=False)
    op.create_index(op.f('ix_transfers_status'), 'transfers', ['status'], unique=False)
    op.create_index(op.f('ix_transfers_token'), 'transfers', ['token'], unique=True)
    op.create_index(op.f('ix_transfers_user_id'), 'transfers', ['user_id'], unique=False)
    op.create_table('usuarios_puertos',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('puerto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['puerto_id'], ['puertos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'puerto_id')
    )
    op.create_table('transfer_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=500), nullable=False),
    sa.Column('stored_name', sa.String(length=500), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('subido_por_id', sa.Integer(), nullable=True),
    sa.Column('es_original', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['subido_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_files_id'), 'transfer_files', ['id'], unique=False)
    op.create_index(op.f('ix_transfer_files_subido_por_id'), 'transfer_files', ['subido_por_id'], unique=False)
    op.create_index(op.f('ix_transfer_files_transfer_id'), 'transfer_files', ['transfer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_files_transfer_id'), table_name='transfer_files')
    op.drop_index(op.f('ix_transfer_files_subido_por_id'), table_name='transfer_files')
    op.drop_index(op.f('ix_transfer_files_id'), table_name='transfer_files')
    op.drop_table('transfer_files')
    op.drop_table('usuarios_puertos')
    op.drop_index(op.f('ix_transfers_user_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_token'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_status'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_puerto_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_id'), table_name='transfers')
    op.drop_index('ix_transfers_expires_at', table_name='transfers')
    op.drop_index(op.f('ix_transfers_carpeta_id'), table_name='transfers')
    op.drop_table('transfers')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_creado_en'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_rol_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_permisos_rol_id'), table_name='roles_permisos')
    op.drop_index(op.f('ix_roles_permisos_permiso_id'), table_name='roles_permisos')
    op.drop_index(op.f('ix_roles_permisos_id'), table_name='roles_permisos')
    op.drop_table('roles_permisos')
    op.drop_index(op.f('ix_carpetas_puerto_id'), table_name='carpetas')
    op.drop_index(op.f('ix_carpetas_id'), table_name='carpetas')
    op.drop_table('carpetas')
    op.drop_index(op.f('ix_roles_nombre'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_puertos_id'), table_name='puertos')
    op.drop_table('puertos')
    op.drop_index(op.f('ix_permisos_id'), table_name='permisos')
    op.drop_index(op.f('ix_permisos_codigo'), table_name='permisos')
    op.drop_table('permisos')
    # ### end Alembic commands ###
